name: flutter_mint
description: A Package for common flutter ui and other utilities
version: 0.0.1
author: Mubarak Asafa<starclick192@gmail.com>
# homepage: https://github.com/mubaraktijani/flutter_mint.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  path: ^1.8.0
  html:
  sentry: any
  sqflite:
  catcher: ^0.3.20
  shimmer: any
  provider: ^5.0.0
  futuristic: any
  velocity_x: ^1.3.1
  mvc_pattern: any
  google_fonts: any
  flutter_spinkit: any
  shared_preferences: ^2.0.3
  flutter_vector_icons: ^1.0.0
  cached_network_image: ^2.3.2+1
  smooth_page_indicator: ^0.2.0
  
dependency_overrides:
  # mailer: ^4.0.0
  # intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700